global-mesagge: its works

spring:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  config:
    import: configserver:http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
