global-mesagge: its works

spring:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
